TARGET := iphone:clang:latest:14.0
ARCHS := arm64 arm64e
TWEAK_NAME := VCamProbe3

VCamProbe3_FILES := Probe3.x
VCamProbe3_CFLAGS := -Wno-unused-variable

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk