TARGET := iphone:clang:latest:14.0
ARCHS := arm64 arm64e
TWEAK_NAME := VCamProbe2

VCamProbe2_FILES := Probe2.x
VCamProbe2_CFLAGS := -Wno-unused-variable

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk